spring:
  redis:
    port: 6379
    host: 192.168.58.136
    database: 0
    password: hoperuo666
    jedis:
      pool:
        max-active: 20
        max-wait: 3000
        max-idle: 10
        min-idle: 0
    timeout: 3000
  cloud:
    bus:
      #enabled: true
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
